# -*- coding: utf-8 -*-
"""SLM4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1docQMhkE2O2GZ3WoeDJtGxjJ08C7bSAH
"""

!pip install transformers datasets accelerate -q

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import Trainer, TrainingArguments

from datasets import load_dataset

dataset = load_dataset("knkarthick/dialogsum")

dataset

def combine(example):
    return {"text": example["dialogue"]}

dataset = dataset.map(combine)

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "distilgpt2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(model_name)

def tokenize(example):
    tokens = tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

tokenized = dataset.map(tokenize, batched=True)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./chatbot_model",
    num_train_epochs=15,
    per_device_train_batch_size=4,
    save_steps=500,
    save_total_limit=1,
    logging_steps=100,
    report_to="none"
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized["train"]
)

trainer.train()

trainer.save_model("./chatbot_model")
tokenizer.save_pretrained("./chatbot_model")

import shutil
shutil.make_archive("chatbot_model", 'zip', "./chatbot_model")

from google.colab import files
files.download("chatbot_model.zip")